name: Dependabot auto merge

on:
  pull_request:
    branches:
      - dependabot/**

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto merge PR
        # see: https://github.com/orgs/community/discussions/129063
        run: gh pr merge --auto --merge "${{ github.event.pull_request.url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
